openapi: 3.0.0

info:
  version: "1.0"
  title: ETSI GS QKD 014 API
  description: ETSI GS QKD 014 API
  
servers:
- url: /api/v1/keys
  description: ETSI GS QKD 014

tags:
- name: Status
  description: Status methods
- name: Key
  description: Key methods

paths:
  /{SAEId}/status:
    get:
      tags:
      - Status
      summary: Get the status object
      operationId: GetStatusObject
      parameters:
      - name: SAEId
        in: path
        description: SAE ID
        required: true
        schema:
          type: string
          example: 'JJJJKKKKLLLL'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
            text/plain:
              schema:
                type: string
        404:
          description: Status key not found
          content: {}
        500:
          description: Internal server error
          content: {}      
  /{SAEId}/enc_keys:
    get:
      tags:
      - Key
      summary: Get the key container object
      operationId: GetKeyContainerObject
      parameters:
      - name: SAEId
        in: path
        description: SAE ID
        required: true
        schema:
          type: string
          example: 'JJJJKKKKLLLL'
      - name: number
        in: query
        description: number
        required: false
        schema:
          type: integer
          example: 1
      - name: size
        in: query
        description: size
        required: false
        schema:
          type: integer
          example: 1024
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
            text/plain:
              schema:
                type: string
        404:
          description: Key container key not found
          content: {}
        500:
          description: Internal server error
          content: {}
    post:
      tags:
      - Key
      summary: Create the key container object
      operationId: CreateKeyContainerObject
      parameters:
      - name: SAEId
        in: path
        description: SAE ID
        required: true
        schema:
          type: string
          example: 'JJJJKKKKLLLL'
      requestBody:
        description: additional_slave_SAE_IDs
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
               number:
                type: integer
               size:
                type: integer
               additional_slave_SAE_IDs:
                type: array
                items:
                  type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
            text/plain:
              schema:
                type: string
        404:
          description: Not found
          content: {}
        500:
          description: Internal server error
          content: {}